---

- name: Creates test directory in the home folder
  file:
    path: $HOME/test
    state: directory

- name: Copy file from master to slave
  copy:
   src: files/test.txt
   dest: $HOME/test/test-copy.txt
...