# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "dbserver" do |dbserver|
    dbserver.vm.box = "ubuntu/bionic64"
  	dbserver.vm.network "private_network", ip: "192.168.56.13", use_dhcp_assigned_default_route: true
  	dbserver.vm.synced_folder "dbserver/", "/vagrant"
  end

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "ubuntu/bionic64"
	webserver.vm.network "private_network", ip: "192.168.56.12", use_dhcp_assigned_default_route: true
	webserver.vm.synced_folder "webserver/", "/vagrant"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
  	ansible.vm.network "private_network", ip: "192.168.56.11", use_dhcp_assigned_default_route: true
  	ansible.vm.synced_folder "ansible/", "/vagrant"
  end
end