---

- name: Playbook Ansible
  hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/default.yml

  tasks:
    - import_tasks: roles/anyrole/tasks/tasks.yml

  handlers:
    - import_tasks: roles/anyrole/handlers/handlers.yml
...
