---

- name: Playbook Ansible Test copy file
  hosts: all
  vars_files:
    - vars/default.yml

  tasks:
    - import_tasks: roles/anyrole/tasks/tasks.yml

    # - import_tasks: roles/anyrole/handlers/handlers.yml
...